services:
  postgres:
    image: postgres:18
    container_name: transcendence-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: backend/dev/Dockerfile
    env_file:
      - backend/dev/.env.docker
    container_name: transcendence-backend

    ports:
      - "4000:4000"

    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules

    restart: unless-stopped

    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: transcendence-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: transcendence-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/dev/Dockerfile

    container_name: transcendence-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres_data: {}
