apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-contact
    receivers:
      # TODO: Add a permanent reciever
      # For quick testing, grab a free URL from https://webhook.site
      - uid: default-webhook
        type: webhook
        settings:
          url: placeholder_url
          httpMethod: POST
        disableResolveMessage: false
