global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scheme: https
    tls_config:
      ca_file: /certs/ca.crt
    static_configs:
      - targets: ['backend:4000']
        labels:
          service: 'transcendence-backend'
