{
 "title": "API-Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(http_requests_total[5m])) by (route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"4..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}