{
 "title": "Backend-Systemhealth",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU-Auslastung (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[2m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(nodejs_eventloop_lag_seconds[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoryusage (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{space=\"old\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "__auto" }
   ]
  }
 ]
}