
/**
 * Generated by Babylon.js Editor
 */

import { loadScene } from "babylonjs-editor-tools";
import * as scripts_single_player from "./scripts/single_player";

export const scriptsMap = {
    "scripts/single_player.ts": scripts_single_player
};

export { loadScene };
